test

diff --git a/.github/workflows/main_cnsclick-web.yml b/.github/workflows/main_cnsclick-web.yml
--- a/.github/workflows/main_cnsclick-web.yml
+++ b/.github/workflows/main_cnsclick-web.yml
@@ -15,7 +15,7 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '18'
+          node-version: '20.x'
           cache: 'npm'
 
       - name: Install dependencies
@@ -23,6 +23,16 @@ jobs:
 
       - name: Build Next.js app
         run: npm run build
+
+      - name: Check if .next folder exists
+        run: |
+          if [ -d ".next" ]; then
+            echo "✅ .next folder found. Here's what's inside:"
+            ls -R .next
+          else
+            echo "❌ .next folder not found."
+            exit 1
+          fi
 
       - name: Prepare standalone deployment
         run: |
