TEST

diff --git a/.github/workflows/main_cnsclick-web.yml b/.github/workflows/main_cnsclick-web.yml
--- a/.github/workflows/main_cnsclick-web.yml
+++ b/.github/workflows/main_cnsclick-web.yml
@@ -26,6 +26,15 @@ jobs:
           npm run build --if-present
           npm run test --if-present
 
+      - name: Check if .next folder exists
+        run: |
+          if [ -d ".next" ]; then
+            echo ".next folder exists ✅"
+          else
+            echo ".next folder is missing ❌"
+            exit 1
+          fi
+
       - name: Prepare standalone folder
         run: |
           cp -R ./public ./.next/standalone/public
